# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ActiveBubo
                                 A QGIS plugin
 ActiveBubo is a python coding project developed as the final assignment for the Python in GIS course. The data provided for the project contained a large dataset of GPS tracks, surveilling the movement of more than 20 Eagle Owls over a time span of several years. Browsing through the available data, it was decided by the group to investigate and answer the following research questions: Which is the month and the season in which the owls are most/least active? Does the temporal scope of owl activity change for different regions? For different owl genders? Which owl is the most active?
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-10
        copyright            : (C) 2018 by Univerity of Muenster
        email                : y_qama01@uni-muenster.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ActiveBubo class from file ActiveBubo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Active_Bubo import ActiveBubo
    return ActiveBubo(iface)
