# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ActiveBuboDialog
                                 A QGIS plugin
 ActiveBubo is a python coding project developed as the final assignment for the Python in GIS course. The data provided for the project contained a large dataset of GPS tracks, surveilling the movement of more than 20 Eagle Owls over a time span of several years. Browsing through the available data, it was decided by the group to investigate and answer the following research questions: Which is the month and the season in which the owls are most/least active? Does the temporal scope of owl activity change for different regions? For different owl genders? Which owl is the most active?
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Univerity of Muenster
        email                : y_qama01@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5 import uic
from PyQt5 import QtWidgets

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Active_Bubo_dialog_base.ui'))


class ActiveBuboDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ActiveBuboDialog, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
